import type { AppNode } from "@/types/flow";
import type { ExportResult } from "./types";
import { SERVICE_MAP } from "./node-map";
import {
  isNetworkContainerNode,
  isVpcNode,
  isSubnetNode,
} from "@/lib/graph-utils";

type Fields = Record<string, string | boolean | number | undefined>;

// ─── Minimal YAML serializer ──────────────────────────────────────────────────

type CfRef = { __cfref: string };

function cfRef(logicalId: string): CfRef {
  return { __cfref: `!Ref ${logicalId}` };
}

function needsYamlQuotes(s: string): boolean {
  if (s === "") return true;
  if (/^(true|false|null|yes|no|on|off)$/i.test(s)) return true;
  if (!isNaN(Number(s))) return true;
  if (/[:{},&*?|<>=!%@`#]/.test(s[0])) return true;
  if (s.includes(": ") || s.includes(" #")) return true;
  if (s.startsWith("- ") || s.startsWith("! ")) return true;
  return false;
}

function yamlScalar(s: string): string {
  if (needsYamlQuotes(s)) {
    return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return s;
}

function yamlValue(v: unknown, indent: number): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (typeof v === "object" && "__cfref" in (v as object)) {
    return (v as CfRef).__cfref;
  }
  if (typeof v === "string") return yamlScalar(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return "[]";
    const pad = "  ".repeat(indent);
    return v
      .map((item) => {
        if (
          typeof item === "object" &&
          item !== null &&
          !("__cfref" in item) &&
          !Array.isArray(item)
        ) {
          const entries = Object.entries(item as Record<string, unknown>).filter(
            ([, val]) => val !== undefined && val !== null,
          );
          if (entries.length === 0) return `${pad}- {}`;
          const [firstKey, firstVal] = entries[0];
          const rest = entries.slice(1);
          const firstLine = `${pad}- ${firstKey}: ${yamlValue(firstVal, indent + 2)}`;
          const restLines = rest.map(
            ([k, val]) => `${pad}  ${k}: ${yamlValue(val, indent + 2)}`,
          );
          return [firstLine, ...restLines].join("\n");
        }
        return `${pad}- ${yamlValue(item, indent + 1)}`;
      })
      .join("\n");
  }
  // Object
  const entries = Object.entries(v as Record<string, unknown>).filter(
    ([, val]) => val !== undefined && val !== null,
  );
  if (entries.length === 0) return "{}";
  const pad = "  ".repeat(indent);
  return entries
    .map(([k, val]) => {
      if (
        typeof val === "object" &&
        val !== null &&
        !("__cfref" in val) &&
        !Array.isArray(val) &&
        Object.keys(val).length > 0
      ) {
        return `${pad}${k}:\n${yamlValue(val, indent + 1)}`;
      }
      if (Array.isArray(val) && val.length > 0) {
        return `${pad}${k}:\n${yamlValue(val, indent + 1)}`;
      }
      return `${pad}${k}: ${yamlValue(val, indent + 1)}`;
    })
    .join("\n");
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function sanitizeCfId(nodeId: string, prefix: string): string {
  const clean = nodeId.replace(/[^a-zA-Z0-9]/g, "").replace(/^[^a-zA-Z]/, "X");
  const cap = prefix.charAt(0).toUpperCase() + prefix.slice(1).replace(/-/g, "");
  const short = clean.slice(-10) || "Node";
  return `${cap}${short}`;
}

function getNodeFields(node: AppNode): Fields {
  return ((node.data as { fields?: Fields }).fields ?? {}) as Fields;
}

function getNodeLabel(node: AppNode): string {
  const data = node.data as {
    label?: string;
    name?: string;
    fields?: { label?: string };
  };
  return data.label ?? data.name ?? data.fields?.label ?? "node";
}

function findAncestorOfType(
  nodeId: string,
  check: (n: AppNode) => boolean,
  byId: Map<string, AppNode>,
): AppNode | undefined {
  const node = byId.get(nodeId);
  if (!node || !node.parentId) return undefined;
  const parent = byId.get(node.parentId);
  if (!parent) return undefined;
  if (check(parent)) return parent;
  return findAncestorOfType(node.parentId, check, byId);
}

function cfResource(
  type: string,
  props: Record<string, unknown>,
): Record<string, unknown> {
  const clean: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(props)) {
    if (v !== undefined && v !== null) clean[k] = v;
  }
  return { Type: type, Properties: clean };
}

const HEADER = `# =============================================================================
# Generated by AWS Architecture Visualizer
#
# DISCLAIMER: This is a starting-point scaffold. Values marked REPLACE_ME
# must be filled in before deploying. Review every resource carefully and
# test in a non-production environment first. The authors accept no
# responsibility for infrastructure changes resulting from this template.
# =============================================================================

AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Architecture - Generated by AWS Architecture Visualizer

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod

`;

function section(title: string): string {
  const bar = "─".repeat(Math.max(0, 73 - title.length));
  return `\n  # ── ${title} ${bar}\n`;
}

function renderResource(logicalId: string, resource: Record<string, unknown>): string {
  const props = resource.Properties as Record<string, unknown>;
  const lines: string[] = [`  ${logicalId}:`];
  lines.push(`    Type: ${resource.Type}`);
  if (props && Object.keys(props).length > 0) {
    lines.push("    Properties:");
    lines.push(yamlValue(props, 3));
  }
  return lines.join("\n");
}

// ─── Main generator ───────────────────────────────────────────────────────────

export function generateCloudFormation(nodes: AppNode[]): ExportResult {
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const parts: string[] = [HEADER, "Resources:"];

  // 1. VPCs
  const vpcs = nodes.filter((n) => isVpcNode(n));
  if (vpcs.length > 0) {
    parts.push(section("VPCs"));
    for (const vpc of vpcs) {
      const id = sanitizeCfId(vpc.id, "Vpc");
      const fields = getNodeFields(vpc);
      const cidr = String(fields.cidrBlock ?? "10.0.0.0/16");
      const resource = cfResource("AWS::EC2::VPC", {
        CidrBlock: cidr,
        EnableDnsSupport: true,
        EnableDnsHostnames: true,
        Tags: [{ Key: "Name", Value: getNodeLabel(vpc) }],
      });
      parts.push(renderResource(id, resource));
    }
  }

  // 2. Subnets
  const subnets = nodes.filter((n) => isSubnetNode(n));
  if (subnets.length > 0) {
    parts.push(section("Subnets"));
    let subnetIdx = 1;
    for (const subnet of subnets) {
      const id = sanitizeCfId(subnet.id, "Subnet");
      const fields = getNodeFields(subnet);
      const data = subnet.data as { subnetType?: string; cidrBlock?: string };
      const cidr = String(
        fields.cidrBlock ?? data.cidrBlock ?? `10.0.${subnetIdx}.0/24`,
      );
      const isPublic =
        (subnet.data as { subnetType?: string }).subnetType === "Public";

      const vpcAncestor = findAncestorOfType(subnet.id, isVpcNode, byId);
      const vpcRefVal = vpcAncestor
        ? cfRef(sanitizeCfId(vpcAncestor.id, "Vpc"))
        : "REPLACE_ME";

      const resource = cfResource("AWS::EC2::Subnet", {
        VpcId: vpcRefVal,
        CidrBlock: cidr,
        MapPublicIpOnLaunch: isPublic,
        Tags: [{ Key: "Name", Value: getNodeLabel(subnet) }],
      });
      parts.push(renderResource(id, resource));
      subnetIdx++;
    }
  }

  // 3. AWS service nodes
  const serviceNodes = nodes.filter(
    (n) => n.type === "awsService" && !isNetworkContainerNode(n),
  );

  const byServiceId: Map<string, AppNode[]> = new Map();
  for (const node of serviceNodes) {
    const serviceId = String(
      (node.data as { serviceId?: string }).serviceId ?? "",
    );
    if (!serviceId) continue;
    const list = byServiceId.get(serviceId) ?? [];
    list.push(node);
    byServiceId.set(serviceId, list);
  }

  const processedResourceTypes = new Set<string>();
  const orderedServiceIds = [...byServiceId.keys()];

  for (const serviceId of orderedServiceIds) {
    const map = SERVICE_MAP[serviceId];
    const cfType = map?.cloudformation ?? null;
    const typeKey = cfType ?? serviceId;

    if (!processedResourceTypes.has(typeKey)) {
      processedResourceTypes.add(typeKey);
      const title = cfType
        ? cfType.split("::").slice(1).join(" ")
        : serviceId.toUpperCase();
      parts.push(section(title));
    }

    const svcNodes = byServiceId.get(serviceId)!;
    for (const node of svcNodes) {
      const logicalId = sanitizeCfId(
        node.id,
        serviceId.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()),
      );
      const fields = getNodeFields(node);

      if (!map?.cloudformation) {
        parts.push(
          `  # ${serviceId} — no direct CloudFormation resource mapping available`,
        );
        parts.push(`  # Service: ${getNodeLabel(node)}\n`);
        continue;
      }

      const serviceProps = map.cfProps ? map.cfProps(fields) : {};

      // Attach subnet/vpc reference
      const subnetAncestor = findAncestorOfType(node.id, isSubnetNode, byId);
      const vpcAncestor = findAncestorOfType(node.id, isVpcNode, byId);

      const locationProps: Record<string, unknown> = {};
      if (subnetAncestor) {
        locationProps.SubnetId = cfRef(sanitizeCfId(subnetAncestor.id, "Subnet"));
      } else if (vpcAncestor) {
        locationProps.VpcId = cfRef(sanitizeCfId(vpcAncestor.id, "Vpc"));
      }

      const props: Record<string, unknown> = {
        ...serviceProps,
        ...locationProps,
        Tags: [{ Key: "Name", Value: getNodeLabel(node) }],
      };

      const resource = cfResource(map.cloudformation, props);
      parts.push(renderResource(logicalId, resource));
    }
  }

  return {
    content: parts.join("\n"),
    filename: "template.yaml",
    mimeType: "text/yaml",
  };
}
